title: Eilarwyn Fine Art Studio
description: Original Art, Inspired by Nature's Wild Beauty

collections:
  artworks:
    output: true

    defaults:
  - scope:
      path: ""
      type: artworks
    values:
      layout: artwork
